/** 初始化应用sql */
INSERT INTO SC_DEPLOY_APPS VALUES('mc','mc','消息服务','1','','',1,'1');
/** 初始化实例信息 */
INSERT INTO SC_DEPLOY_APPS_INSTANCES VALUES('1','mc_01_1301','mc','','127.0.0.1','8090','1301');

/** 初始化参数定义 */
INSERT INTO SC_PARAMS_DEF (PARAM_ID,PARAM_CODE,PARAM_TEXT,PARAM_DISPLAY_TYPE,PARAM_VAL_ITEMS,PROP_DEF_VALALUE,MODULE_CODE,DESCRIPTION,SEQ)
VALUES('MC0001','Mc.messageGroupCount','消息服务分组处理消息数量','0','','','mc','每次消息队列处理消息数量',1);

INSERT INTO SC_PARAMS_DEF (PARAM_ID,PARAM_CODE,PARAM_TEXT,PARAM_DISPLAY_TYPE,PARAM_VAL_ITEMS,PROP_DEF_VALALUE,MODULE_CODE,DESCRIPTION,SEQ)
VALUES('MC0002','Mc.errorHandleSleepTime','失败队列处理线程休眠时间（s）','0','','','mc','失败队列处理线程休眠时间（s）',2);

INSERT INTO SC_PARAMS_DEF (PARAM_ID,PARAM_CODE,PARAM_TEXT,PARAM_DISPLAY_TYPE,PARAM_VAL_ITEMS,PROP_DEF_VALALUE,MODULE_CODE,DESCRIPTION,SEQ)
VALUES('MC0003','Mc.logSwitch','消息服务集成日志中心开关','3','true:开启#false:关闭','false','mc','消息服务集成日志中心统一开关',3);

INSERT INTO SC_PARAMS_DEF (PARAM_ID,PARAM_CODE,PARAM_TEXT,PARAM_DISPLAY_TYPE,PARAM_VAL_ITEMS,PROP_DEF_VALALUE,MODULE_CODE,DESCRIPTION,SEQ)
VALUES('MC0004','Mc.messageSenderImplPath','消息发送器路径','0','','','mc','消息发送器路径',4);

/** 初始化参数值 */
INSERT INTO SC_PARAMS_VALUE (VALUE_ID,PARAM_CODE,APP_CODE,APP_INSTANCE_CODE,PARAM_TEXT,PARAM_EFFECTIVE_RANGE,PARAM_VALUE)
VALUES('MC000101','Mc.messageGroupCount','mc',NULL,'消息服务分组处理消息数量','0','100');

INSERT INTO SC_PARAMS_VALUE (VALUE_ID,PARAM_CODE,APP_CODE,APP_INSTANCE_CODE,PARAM_TEXT,PARAM_EFFECTIVE_RANGE,PARAM_VALUE)
VALUES('MC000201','Mc.errorHandleSleepTime','mc',NULL,'失败队列处理线程休眠时间（s）','0','10');

INSERT INTO SC_PARAMS_VALUE (VALUE_ID,PARAM_CODE,APP_CODE,APP_INSTANCE_CODE,PARAM_TEXT,PARAM_EFFECTIVE_RANGE,PARAM_VALUE)
VALUES('MC000301','Mc.logSwitch','mc',NULL,'消息服务集成日志中心开关','3','false');

INSERT INTO SC_PARAMS_VALUE (VALUE_ID,PARAM_CODE,APP_CODE,APP_INSTANCE_CODE,PARAM_TEXT,PARAM_EFFECTIVE_RANGE,PARAM_VALUE)
VALUES('MC000401','Mc.messageSenderImplPath','mc',NULL,'消息发送器路径','0','com.inspur.gcloud.ext.sender.impl.ShortMessageSenderImpl');
