-- 回执表建表sql
CREATE TABLE MC_RECEIPT
(
	ID      VARCHAR2(32) NOT NULL,    --  回执ID 
	SEND_ID VARCHAR2(32),    --  发送人ID 
	RECEIVER_ID VARCHAR2(32),    --  收件人ID 
	MESSAGE_ID VARCHAR2(32),    --  关联消息ID 
	RECEIPT_INFOMATION VARCHAR2(50)    --  回执信息 
);

COMMENT ON TABLE MC_RECEIPT IS '回执表,回执信息';
COMMENT ON COLUMN MC_RECEIPT.ID      IS '回执ID';
COMMENT ON COLUMN MC_RECEIPT.SEND_ID IS '发送人ID';
COMMENT ON COLUMN MC_RECEIPT.RECEIVER_ID IS '收件人ID';
COMMENT ON COLUMN MC_RECEIPT.MESSAGE_ID IS '关联消息ID';
COMMENT ON COLUMN MC_RECEIPT.RECEIPT_INFOMATION IS '回执信息';

-- 订阅记录建表sql
CREATE TABLE MC_SUBSCRIBE
(
	ID      VARCHAR2(32) NOT NULL,    --  ID 
	ORGAN_ID VARCHAR2(32),    --  组织代码 
	SUBSCRIBE_MODULE VARCHAR2(100),    --  订阅模块 
	WARN_TYPE VARCHAR2(2),    --  提醒方式：m：站内消息；w：站内邮件；           s：短信；    e：电子邮件； 
	SUBSCRIBE_OPEN VARCHAR2(2),    --  是否开启订阅：0：否；1：是 
	REMARK  VARCHAR2(50)    --  备注 
);

COMMENT ON TABLE MC_SUBSCRIBE IS '订阅记录表';
COMMENT ON COLUMN MC_SUBSCRIBE.ID      IS 'ID';
COMMENT ON COLUMN MC_SUBSCRIBE.ORGAN_ID IS '组织代码';
COMMENT ON COLUMN MC_SUBSCRIBE.SUBSCRIBE_MODULE IS '订阅模块';
COMMENT ON COLUMN MC_SUBSCRIBE.WARN_TYPE IS '提醒方式：m：站内消息；w：站内邮件；           s：短信；    e：电子邮件；';
COMMENT ON COLUMN MC_SUBSCRIBE.SUBSCRIBE_OPEN IS '是否开启订阅：0：否；1：是';
COMMENT ON COLUMN MC_SUBSCRIBE.REMARK  IS '备注';

-- 附件建表sql
CREATE TABLE MC_ATTACH
(
	ATTACH_ID VARCHAR2(32) NOT NULL,    --  附件ID，主键 
	ATTACH_NAME VARCHAR2(50),    --  附件名称 
	ATTACH_TYPE VARCHAR2(50),    --  附件类型 
	MEMORY_TYPE VARCHAR2(1),    --  存储类型：0：网盘；1：本地 
	ATTACH_ADDRESS VARCHAR2(100),    --  附件的地址 
	CREATE_TIME DATE,    --  创建时间 
	UPDATE_TIME DATE,    --  修改时间 
	REMARK VARCHAR2(50)    --  备注 
);

COMMENT ON TABLE MC_ATTACH IS '附件表，存储附件信息';
COMMENT ON COLUMN MC_ATTACH.ATTACH_ID IS '附件ID，主键';
COMMENT ON COLUMN MC_ATTACH.ATTACH_NAME IS '附件名称';
COMMENT ON COLUMN MC_ATTACH.ATTACH_TYPE IS '附件类型';
COMMENT ON COLUMN MC_ATTACH.MEMORY_TYPE IS '存储类型：0：网盘；1：本地';
COMMENT ON COLUMN MC_ATTACH.ATTACH_ADDRESS IS '附件的地址';
COMMENT ON COLUMN MC_ATTACH.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MC_ATTACH.UPDATE_TIME IS '修改时间';
COMMENT ON COLUMN MC_ATTACH.REMARK IS '备注';

-- 历史附件建表sql
CREATE TABLE MC_ATTACH_HISTORY
(
	ATTACH_ID VARCHAR2(32) NOT NULL,    --  附件ID，主键 
	ATTACH_NAME VARCHAR2(50),    --  附件名称 
	ATTACH_TYPE VARCHAR2(50),    --  附件类型 
	MEMORY_TYPE VARCHAR2(1),    --  存储类型：0：网盘；1：本地 
	ATTACH_ADDRESS VARCHAR2(100),    --  附件的地址 
	CREATE_TIME DATE,    --  创建时间 
	UPDATE_TIME DATE,    --  修改时间 
	REMARK VARCHAR2(50)    --  备注 
);

COMMENT ON TABLE MC_ATTACH_HISTORY IS '历史附件表，存储附件信息';
COMMENT ON COLUMN MC_ATTACH_HISTORY.ATTACH_ID IS '附件ID，主键';
COMMENT ON COLUMN MC_ATTACH_HISTORY.ATTACH_NAME IS '附件名称';
COMMENT ON COLUMN MC_ATTACH_HISTORY.ATTACH_TYPE IS '附件类型';
COMMENT ON COLUMN MC_ATTACH_HISTORY.MEMORY_TYPE IS '存储类型：0：网盘；1：本地';
COMMENT ON COLUMN MC_ATTACH_HISTORY.ATTACH_ADDRESS IS '附件的地址';
COMMENT ON COLUMN MC_ATTACH_HISTORY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MC_ATTACH_HISTORY.UPDATE_TIME IS '修改时间';
COMMENT ON COLUMN MC_ATTACH_HISTORY.REMARK IS '备注';

-- 历史信封建表sql
CREATE TABLE MC_ENVELOPE_HISTORY
(
	ID      VARCHAR2(32) NOT NULL,    --  ID 
	MESSAGE_ID VARCHAR2(32) NOT NULL,    --  消息ID 
	MESSAGE_TOPIC VARCHAR2(200),    --  消息主题 
	MESSAGE_TYPE VARCHAR2(2),    --  消息类型：m：站内消息；w：站内邮件；           s：短信；    e：电子邮件； 
	RELATED_MESSAGE_ID VARCHAR2(32),    --  转发或回复时消息的原消息ID，原始消息的关联消息ID为本身ID 
	RELATED_PATH    VARCHAR2(500),    --  关联路径：转发或回复该消息的所有消息ID 
	SENDER_ID VARCHAR2(32) NOT NULL,    --  发件人ID 
	SENDER_NAME VARCHAR2(32) NOT NULL,	--  发件人NAME
	RECEIVER_ID VARCHAR2(32),    --  收件人ID：可为多个，也可为一个组织或机构 
	RECEIVER_NAME VARCHAR2(32),	 --  收件人NAME：可为多个，也可为一个组织或机构 
	RECEIVE_STATE VARCHAR(1),    --  收件状态：0：未读；1：已读；2：删除；           3：彻底删除；null：未接收； 
	SEND_STATE VARCHAR(1),    --  发送状态：0：未发送；1：已发送；2：删除；           3：彻底删除 
	IS_SCHEDULE  VARCHAR2(1),    --  是否定时发送：0：否；1：是； 
	IS_READ_RECEIPT VARCHAR2(1),    --  是否需要回执：0：否；1：是； 
	HAS_RECEIPT VARCHAR2(1),    --  是否已回执：0：否；1：是； 
	SEND_TYPE VARCHAR2(1),    --  发送类型：0：原邮件；1：回复；2：转发 
	RECEIVER_TYPE VARCHAR2(50),    --  收件人类型：一对一；all：系统消息； 
	SEND_LEVEL VARCHAR2(1),    --  是否抄送：0：主送；1：抄送； 
	SEND_TIME DATE,    --  发送时间 
	READ_TIME DATE,    --  阅读时间 
	CREATE_TIME DATE,    --  创建时间 
	UPDATE_TIME DATE,    --  修改时间 
	REMARK  VARCHAR2(50)    --  备注  
);
COMMENT ON TABLE MC_ENVELOPE_HISTORY IS '历史信封表；用户消息关联';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.ID      IS 'ID';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.MESSAGE_ID IS '消息ID';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.MESSAGE_TOPIC IS '消息主题';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.MESSAGE_TYPE IS '消息类型：m：站内消息；w：站内邮件；           s：短信；    e：电子邮件；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.RELATED_MESSAGE_ID IS '转发或回复时消息的原消息ID，原始消息的关联消息ID为本身ID';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.PATH    IS '关联路径：转发或回复该消息的所有消息ID';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.SENDER_ID IS '发件人ID';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.SENDER_NAME IS '发件人NAME';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.RECEIVER_ID IS '收件人ID：可为多个，也可为一个组织或机构';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.RECEIVER_NAME IS '收件人NAME：可为多个，也可为一个组织或机构';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.RECEIVE_STATE IS '收件状态：0：未读；1：已读；2：删除；           3：彻底删除；null：未接收；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.SEND_STATE IS '发送状态：0：未发送；1：已发送；2：删除；           3：彻底删除';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.TIMING  IS '是否定时发送：0：否；1：是；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.READ_RECEIPT IS '是否需要回执：0：否；1：是；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.HAS_RECEIPT IS '是否已回执：0：否；1：是；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.SEND_TYPE IS '发送类型：0：原邮件；1：回复；2：转发';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.RECEIVER_TYPE IS '收件人类型：一对一；all：系统消息；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.SEND_LEVEL IS '是否抄送：0：主送；1：抄送；';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.SEND_TIME IS '发送时间';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.READ_TIME IS '阅读时间';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.UPDATE_TIME IS '修改时间';
COMMENT ON COLUMN MC_ENVELOPE_HISTORY.REMARK  IS '备注';


-- 历史信息建表sql
CREATE TABLE MC_MESSAGE_HISTORY
(
	MESSAGE_ID VARCHAR2(32) NOT NULL,    --  消息ID 
	MESSAGE_TOPIC VARCHAR2(200),    --  消息主题 
	MESSAGE_CONTENT VARCHAR2(500),    --  消息内容 
	MAIL_ATTACH_ID VARCHAR2(32),    --  邮件附件；消息无附件； 
	REMARK VARCHAR2(50)    --  备注 
);

COMMENT ON TABLE MC_MESSAGE_HISTORY IS '历史消息表';
COMMENT ON COLUMN MC_MESSAGE_HISTORY.MESSAGE_ID IS '消息ID';
COMMENT ON COLUMN MC_MESSAGE_HISTORY.MESSAGE_TOPIC IS '消息主题';
COMMENT ON COLUMN MC_MESSAGE_HISTORY.MESSAGE_CONTENT IS '消息内容';
COMMENT ON COLUMN MC_MESSAGE_HISTORY.MAIL_ATTACH_ID IS '邮件附件；消息无附件；';
COMMENT ON COLUMN MC_MESSAGE_HISTORY.REMARK IS '备注';

-- 信封建表sql
CREATE TABLE MC_ENVELOPE
(
	ID      VARCHAR2(32) NOT NULL,    --  ID 
	MESSAGE_ID VARCHAR2(32) NOT NULL,    --  消息ID 
	MESSAGE_TOPIC VARCHAR2(200),    --  消息主题 
	MESSAGE_TYPE VARCHAR2(2),    --  消息类型：m：站内消息；w：站内邮件；           s：短信；    e：电子邮件； 
	RELATED_MESSAGE_ID VARCHAR2(32),    --  转发或回复时消息的原消息ID，原始消息的关联消息ID为本身ID 
	RELATED_PATH    VARCHAR2(500),    --  关联路径：转发或回复该消息的所有消息ID 
	SENDER_ID VARCHAR2(32) NOT NULL,    --  发件人ID 
	SENDER_NAME VARCHAR2(32) NOT NULL,	--  发件人NAME
	RECEIVER_ID VARCHAR2(32),    --  收件人ID：可为多个，也可为一个组织或机构 
	RECEIVER_NAME VARCHAR2(32),    --  收件人NAME：可为多个，也可为一个组织或机构 
	RECEIVE_STATE VARCHAR(1),    --  收件状态：0：未读；1：已读；2：删除；           3：彻底删除；null：未接收； 
	SEND_STATE VARCHAR(1),    --  发送状态：0：未发送；1：已发送；2：删除；           3：彻底删除 
	IS_SCHEDULE  VARCHAR2(1),    --  是否定时发送：0：否；1：是； 
	IS_READ_RECEIPT VARCHAR2(1),    --  是否需要回执：0：否；1：是； 
	HAS_RECEIPT VARCHAR2(1),    --  是否已回执：0：否；1：是； 
	SEND_TYPE VARCHAR2(1),    --  发送类型：0：原邮件；1：回复；2：转发 
	RECEIVER_TYPE VARCHAR2(50),    --  收件人类型：一对一；all：系统消息； 
	SEND_LEVEL VARCHAR2(1),    --  是否抄送：0：主送；1：抄送； 
	SEND_TIME DATE,    --  发送时间 
	READ_TIME DATE,    --  阅读时间 
	CREATE_TIME DATE,    --  创建时间 
	UPDATE_TIME DATE,    --  修改时间 
	REMARK  VARCHAR2(50)    --  备注 
);

COMMENT ON TABLE MC_ENVELOPE IS '信封表；用户消息关联';
COMMENT ON COLUMN MC_ENVELOPE.ID      IS 'ID';
COMMENT ON COLUMN MC_ENVELOPE.MESSAGE_ID IS '消息ID';
COMMENT ON COLUMN MC_ENVELOPE.MESSAGE_TOPIC IS '消息主题';
COMMENT ON COLUMN MC_ENVELOPE.MESSAGE_TYPE IS '消息类型：m：站内消息；w：站内邮件；           s：短信；    e：电子邮件；';
COMMENT ON COLUMN MC_ENVELOPE.RELATED_MESSAGE_ID IS '转发或回复时消息的原消息ID，原始消息的关联消息ID为本身ID';
COMMENT ON COLUMN MC_ENVELOPE.PATH    IS '关联路径：转发或回复该消息的所有消息ID';
COMMENT ON COLUMN MC_ENVELOPE.SENDER_ID IS '发件人ID';
COMMENT ON COLUMN MC_ENVELOPE.SENDER_NAME IS '发件人NAME';
COMMENT ON COLUMN MC_ENVELOPE.RECEIVER_ID IS '收件人ID：可为多个，也可为一个组织或机构';
COMMENT ON COLUMN MC_ENVELOPE.RECEIVER_NAME IS '收件人NAME：可为多个，也可为一个组织或机构';
COMMENT ON COLUMN MC_ENVELOPE.RECEIVE_STATE IS '收件状态：0：未读；1：已读；2：删除；           3：彻底删除；null：未接收；';
COMMENT ON COLUMN MC_ENVELOPE.SEND_STATE IS '发送状态：0：未发送；1：已发送；2：删除；           3：彻底删除';
COMMENT ON COLUMN MC_ENVELOPE.TIMING  IS '是否定时发送：0：否；1：是；';
COMMENT ON COLUMN MC_ENVELOPE.READ_RECEIPT IS '是否需要回执：0：否；1：是；';
COMMENT ON COLUMN MC_ENVELOPE.HAS_RECEIPT IS '是否已回执：0：否；1：是；';
COMMENT ON COLUMN MC_ENVELOPE.SEND_TYPE IS '发送类型：0：原邮件；1：回复；2：转发';
COMMENT ON COLUMN MC_ENVELOPE.RECEIVER_TYPE IS '收件人类型：一对一；all：系统消息；';
COMMENT ON COLUMN MC_ENVELOPE.SEND_LEVEL IS '是否抄送：0：主送；1：抄送；';
COMMENT ON COLUMN MC_ENVELOPE.SEND_TIME IS '发送时间';
COMMENT ON COLUMN MC_ENVELOPE.READ_TIME IS '阅读时间';
COMMENT ON COLUMN MC_ENVELOPE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MC_ENVELOPE.UPDATE_TIME IS '修改时间';
COMMENT ON COLUMN MC_ENVELOPE.REMARK  IS '备注';

-- 信息表建表sql
CREATE TABLE MC_MESSAGE
(
	MESSAGE_ID VARCHAR2(32) NOT NULL,    --  消息ID 
	MESSAGE_TOPIC VARCHAR2(200),    --  消息主题 
	MESSAGE_CONTENT VARCHAR2(500),    --  消息内容 
	MAIL_ATTACH_ID VARCHAR2(32),    --  邮件附件；消息无附件； 
	REMARK VARCHAR2(50)    --  备注 
);

COMMENT ON TABLE MC_MESSAGE IS '消息表';
COMMENT ON COLUMN MC_MESSAGE.MESSAGE_ID IS '消息ID';
COMMENT ON COLUMN MC_MESSAGE.MESSAGE_TOPIC IS '消息主题';
COMMENT ON COLUMN MC_MESSAGE.MESSAGE_CONTENT IS '消息内容';
COMMENT ON COLUMN MC_MESSAGE.MAIL_ATTACH_ID IS '邮件附件；消息无附件；';
COMMENT ON COLUMN MC_MESSAGE.REMARK IS '备注';


ALTER TABLE MC_RECEIPT ADD CONSTRAINT PK_MC_RECEIPT 
	PRIMARY KEY (ID);

ALTER TABLE MC_SUBSCRIBE ADD CONSTRAINT PK_MC_SUBSCRIBE 
	PRIMARY KEY (ID);

ALTER TABLE MC_ATTACH ADD CONSTRAINT PK_MC_ATTACH 
	PRIMARY KEY (ATTACH_ID);

ALTER TABLE MC_ATTACH_HISTORY ADD CONSTRAINT PK_MC_ATTACH_HISTORY 
	PRIMARY KEY (ATTACH_ID);

ALTER TABLE MC_ENVELOPE_HISTORY ADD CONSTRAINT PK_MC_ENVELOPE_HISTORY 
	PRIMARY KEY (ID);

ALTER TABLE MC_MESSAGE_HISTORY ADD CONSTRAINT PK_MC_MESSAGE_HISTORY 
	PRIMARY KEY (MESSAGE_ID);

ALTER TABLE MC_ENVELOPE ADD CONSTRAINT PK_MC_ENVELOPE 
	PRIMARY KEY (ID);

ALTER TABLE MC_MESSAGE ADD CONSTRAINT PK_MC_MESSAGE 
	PRIMARY KEY (MESSAGE_ID);



ALTER TABLE MC_RECEIPT ADD CONSTRAINT FK_回执表_消息表 
	FOREIGN KEY (MESSAGE_ID) REFERENCES MC_MESSAGE (MESSAGE_ID);

ALTER TABLE MC_ENVELOPE ADD CONSTRAINT FK_信封表_消息表 
	FOREIGN KEY (MESSAGE_ID) REFERENCES MC_MESSAGE (MESSAGE_ID);

ALTER TABLE MC_MESSAGE ADD CONSTRAINT FK_邮件表_附件表 
	FOREIGN KEY (MAIL_ATTACH_ID) REFERENCES MC_ATTACH (ATTACH_ID);
