-- 附件表建表SQL
CREATE TABLE MC_ATTACH (
  ATTACH_ID VARCHAR(32) NOT NULL COMMENT '附件ID，主键',
  MESSAGE_ID VARCHAR(32) NOT NULL COMMENT '关联消息ID',
  ATTACH_NAME VARCHAR(50)  COMMENT '附件名称',
  ATTACH_TYPE VARCHAR(50)  COMMENT '附件类型',
  MEMORY_TYPE VARCHAR(2)  COMMENT '存储类型：0：网盘；1：本地',
  ATTACH_ADDRESS VARCHAR(100)  COMMENT '附件的地址',
  CREATE_TIME DATETIME  COMMENT '创建时间',
  UPDATE_TIME DATETIME  COMMENT '修改时间',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (ATTACH_ID)
) COMMENT='附件表，存储附件信息';

-- 历史附件表建表SQL
CREATE TABLE MC_ATTACH_HISTORY (
  ATTACH_ID VARCHAR(32) NOT NULL COMMENT '附件ID，主键',
  MESSAGE_ID VARCHAR(32) NOT NULL COMMENT '关联消息ID',
  ATTACH_NAME VARCHAR(50)  COMMENT '附件名称',
  ATTACH_TYPE VARCHAR(50)  COMMENT '附件类型',
  MEMORY_TYPE VARCHAR(2)  COMMENT '存储类型：0：网盘；1：本地',
  ATTACH_ADDRESS VARCHAR(100)  COMMENT '附件的地址',
  CREATE_TIME DATETIME  COMMENT '创建时间',
  UPDATE_TIME DATETIME  COMMENT '修改时间',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (ATTACH_ID)
) COMMENT='历史附件表，存储附件信息';


-- 信封表建表SQL
CREATE TABLE MC_ENVELOPE (
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  MESSAGE_ID VARCHAR(32) NOT NULL COMMENT '消息ID',
  MESSAGE_TOPIC VARCHAR(200)  COMMENT '消息主题',
  MESSAGE_TYPE VARCHAR(2)  COMMENT '消息类型：M：站内消息；W：站内邮件；S：短信；E：电子邮件；',
  RELATED_MESSAGE_ID VARCHAR(32)  COMMENT '转发或回复时消息的原消息ID，原始消息的关联消息ID为本身ID',
  RELATED_PATH VARCHAR(32)  COMMENT '关联路径：转发或回复该消息的所有消息ID',
  SENDER_ID VARCHAR(32) NOT NULL COMMENT '发件人ID',
  RECEIVER_ID VARCHAR(32)  COMMENT '收件人ID',
  RECEIVE_STATE VARCHAR(2)  COMMENT '收件状态：0：未读；1：已读；2：删除；3：彻底删除；NULL：未接收；',
  SEND_STATE VARCHAR(2)  COMMENT '发送状态：0：未发送；1：已发送；2：删除；3：彻底删除',
  IS_SCHEDULE VARCHAR(2)  COMMENT '是否定时发送：0：否；1：是；',
  IS_READ_RECEIPT VARCHAR(2)  COMMENT '是否需要回执：0：否；1：是；',
  HAS_RECEIPT VARCHAR(2)  COMMENT '是否已回执：0：否；1：是；',
  SEND_TYPE VARCHAR(2)  COMMENT '发送类型：0：原邮件；1：回复；2：转发',
  RECEIVER_TYPE VARCHAR(2)  COMMENT '收件人类型：0：一对一；1：组织机构代码；3：系统消息；',
  SEND_LEVEL VARCHAR(2)  COMMENT '是否抄送：0：主送；1：抄送；',
  SEND_TIME DATETIME  COMMENT '发送时间',
  READ_TIME DATETIME  COMMENT '阅读时间',
  CREATE_TIME DATETIME  COMMENT '创建时间',
  UPDATE_TIME DATETIME  COMMENT '修改时间',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (ID)
) COMMENT='信封表；用户消息关联';

-- 历史信封表建表SQL
CREATE TABLE MC_ENVELOPE_HISTORY (
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  MESSAGE_ID VARCHAR(32) NOT NULL COMMENT '消息ID',
  MESSAGE_TOPIC VARCHAR(200)  COMMENT '消息主题',
  MESSAGE_TYPE VARCHAR(2)  COMMENT '消息类型：M：站内消息；W：站内邮件；S：短信；E：电子邮件；',
  RELATED_MESSAGE_ID VARCHAR(32)  COMMENT '转发或回复时消息的原消息ID，原始消息的关联消息ID为本身ID',
  RELATED_PATH VARCHAR(32)  COMMENT '关联路径：转发或回复该消息的所有消息ID',
  SENDER_ID VARCHAR(32) NOT NULL COMMENT '发件人ID',
  RECEIVER_ID VARCHAR(32)  COMMENT '收件人ID',
  RECEIVE_STATE VARCHAR(2)  COMMENT '收件状态：0：未读；1：已读；2：删除；3：彻底删除；NULL：未接收；',
  SEND_STATE VARCHAR(2)  COMMENT '发送状态：0：未发送；1：已发送；2：删除；3：彻底删除',
  IS_SCHEDULE VARCHAR(2)  COMMENT '是否定时发送：0：否；1：是；',
  IS_READ_RECEIPT VARCHAR(2)  COMMENT '是否需要回执：0：否；1：是；',
  HAS_RECEIPT VARCHAR(2)  COMMENT '是否已回执：0：否；1：是；',
  SEND_TYPE VARCHAR(2)  COMMENT '发送类型：0：原邮件；1：回复；2：转发',
  RECEIVER_TYPE VARCHAR(2)  COMMENT '收件人类型：0：一对一；1：组织机构代码；3：系统消息；',
  SEND_LEVEL VARCHAR(2)  COMMENT '是否抄送：0：主送；1：抄送；',
  SEND_TIME DATETIME  COMMENT '发送时间',
  READ_TIME DATETIME  COMMENT '阅读时间',
  CREATE_TIME DATETIME  COMMENT '创建时间',
  UPDATE_TIME DATETIME  COMMENT '修改时间',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (ID)
) COMMENT='历史信封表，用户消息关联表';

-- 信息表建表SQL
CREATE TABLE MC_MESSAGE (
  MESSAGE_ID VARCHAR(32) NOT NULL COMMENT '消息ID',
  MESSAGE_LEVEL VARCHAR(2) COMMENT '消息级别：0为最低级别，9为最高级别',
  MESSAGE_TOPIC VARCHAR(200)  COMMENT '消息主题',
  MESSAGE_CONTENT TEXT COMMENT '消息内容',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (MESSAGE_ID)
) COMMENT='消息表';

-- 历史信息表建表SQL
CREATE TABLE MC_MESSAGE_HISTORY (
  MESSAGE_ID VARCHAR(32) NOT NULL COMMENT '消息ID',
  MESSAGE_LEVEL VARCHAR(2) COMMENT '消息级别：0为最低级别，9为最高级别',
  MESSAGE_TOPIC VARCHAR(200)  COMMENT '消息主题',
  MESSAGE_CONTENT TEXT COMMENT '消息内容',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (MESSAGE_ID)
) COMMENT='历史消息表';

-- 回执表建表SQL
CREATE TABLE MC_RECEIPT (
  ID VARCHAR(32) NOT NULL COMMENT '回执ID',
  SEND_ID VARCHAR(32)  COMMENT '发送人ID',
  RECEIVER_ID VARCHAR(32)  COMMENT '收件人ID',
  MESSAGE_ID VARCHAR(32)  COMMENT '关联消息ID',
  RECEIPT_INFOMATION VARCHAR(200)  COMMENT '回执信息',
  PRIMARY KEY  (ID)
) COMMENT='回执表,回执信息';

-- 订阅记录表建表SQL
CREATE TABLE MC_SUBSCRIBE (
  ID VARCHAR(32) NOT NULL COMMENT 'ID',
  ORGAN_ID VARCHAR(32)  COMMENT '组织代码',
  SUBSCRIBE_MODULE VARCHAR(100)  COMMENT '订阅模块',
  WARN_TYPE VARCHAR(2)  COMMENT '提醒方式：M：站内消息；W：站内邮件；S：短信；E：电子邮件；',
  SUBSCRIBE_OPEN VARCHAR(2)  COMMENT '是否开启订阅：0：否；1：是',
  REMARK VARCHAR(50)  COMMENT '备注',
  PRIMARY KEY  (ID)
) COMMENT='订阅记录表';
