-- 应用
INSERT INTO PUB_APPS(APP_CODE, APP_NAME, TRANSPORT, SERVER_HOST, PORT, CONTEXT, URI, SEQ, NOTE)
VALUES ('APPMC', '消息', 'http', '10.12.1.80', '80', 'mc', 'http://10.12.1.80:80/mc', 13, NULL);
-- 模块
INSERT INTO PUB_MODULES (MODULE_CODE,MODULE_NAME,PARENT_MODULE_CODE,IS_LEAF_MODULE,APP_CODE,MODULE_PATH,MODULE_PATH_NAME,SEQ) 
VALUES('MC',' 消息','-1','0','APPMC','MC','消息',0);