-- 角色设置
-- 名称核准_系统管理人员
INSERT INTO PUB_ROLES(ROLE_ID, ROLE_NAME, RELATION_ID, ROLE_GROUP_ID, DESCRIPTION, ROLE_CODE, ORGAN_TYPE, IS_GLOBAL, CTIME) VALUES 
('MC_ADMINISTRATOR', '消息_系统管理人员', '1', '' , '消息_系统管理人员' , '' ,'' ,'' ,'2015-01-06 10:27:32');

-- 名称核准_审批人员
INSERT INTO PUB_ROLES(ROLE_ID, ROLE_NAME, RELATION_ID, ROLE_GROUP_ID, DESCRIPTION, ROLE_CODE, ORGAN_TYPE, IS_GLOBAL, CTIME) VALUES 
('MC_USER', '消息_审批人员', '1', '' , '消息_审批人员' , '' ,'' ,'' ,'2015-01-06 10:27:32');