-- 菜单
-- 站内消息
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,MODULE_CODE,APP_CODE)
VALUES('MC_INSTATIONMSG','站内消息','MC_INSTATIONMSG','APPMC');
-- 收件箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_INSTATIONMSG_01','收件箱','jsp/mc/instationmessage/inbox/msg_inbox_query.jsp','1','MC_INSTATIONMSG','MC_INSTATIONMSG_01','APPMC');
-- 发件箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_INSTATIONMSG_02','发件箱','jsp/mc/instationmessage/outbox/msg_outbox_query.jsp','1','MC_INSTATIONMSG','MC_INSTATIONMSG_02','APPMC');
-- 草稿箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_INSTATIONMSG_03','草稿箱','jsp/mc/instationmessage/draftbox/msg_draftbox_query.jsp','1','MC_INSTATIONMSG','MC_INSTATIONMSG_03','APPMC');
-- 废件箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_INSTATIONMSG_04','废件箱','jsp/mc/instationmessage/scrapbox/msg_scrapbox_query.jsp','1','MC_INSTATIONMSG','MC_INSTATIONMSG_04','APPMC');

-- 菜单关系
-- 站内消息
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_INSTATIONMSG','1','MC_INSTATIONMSG','MC',1,'MC#MC_INSTATIONMSG','消息#站内消息');
-- 收件箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_INSTATIONMSG_01','1','MC_INSTATIONMSG_01','MC_INSTATIONMSG',2,'MC#MC_INSTATIONMSG#MC_INSTATIONMSG_01','消息#站内消息#收件箱');
-- 发件箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_INSTATIONMSG_02','1','MC_INSTATIONMSG_02','MC_INSTATIONMSG',3,'MC#MC_INSTATIONMSG#MC_INSTATIONMSG_02','消息#站内消息#发件箱');
-- 草稿箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_INSTATIONMSG_03','1','MC_INSTATIONMSG_03','MC_INSTATIONMSG',4,'MC#MC_INSTATIONMSG#MC_INSTATIONMSG_03','消息#站内消息#草稿箱');
-- 废件箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_INSTATIONMSG_04','1','MC_INSTATIONMSG_04','MC_INSTATIONMSG',5,'MC#MC_INSTATIONMSG#MC_INSTATIONMSG_04','消息#站内消息#废件箱');

-- 菜单
-- 短信
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,MODULE_CODE,APP_CODE)
VALUES('MC_MSG','短信','MC_MSG','APPMC');
-- 发件箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_MSG_01','发件箱','jsp/mc/message/outbox/msg_outbox_query.jsp','1','MC_MSG','MC_MSG_01','APPMC');
-- 草稿箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_MSG_02','草稿箱','jsp/mc/message/draftbox/msg_draftbox_query.jsp','1','MC_MSG','MC_MSG_02','APPMC');
-- 废件箱
INSERT INTO PUB_MENU_ITEM(MENU_ID,MENU_NAME,REQUEST_ACTION,IS_LEAF,MODULE_CODE,FUNCTION_CODE,APP_CODE) 
VALUES('MC_MSG_03','废件箱','jsp/mc/message/scrapbox/msg_scrapbox_query.jsp','1','MC_MSG','MC_MSG_03','APPMC');

-- 菜单关系
-- 短息
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_MSG','1','MC_MSG','MC',1,'MC#MC_MSG','消息#短信');
-- 发件箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_MSG_01','1','MC_MSG_01','MC_MSG',2,'MC#MC_MSG#MC_MSG_01','消息#短息#发件箱');
-- 草稿箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_MSG_02','1','MC_MSG_02','MC_MSG',3,'MC#MC_MSG#MC_MSG_02','消息#短息#草稿箱');
-- 废件箱
INSERT INTO PUB_MENU_STRU(MENU_STRU_ID,MENU_TYPE_ID,MENU_ID,PARENT_MENU_ID,SEQ,MENU_PATH,PATH_NAME) 
VALUES ('MC_MSG_03','1','MC_MSG_03','MC_MSG',4,'MC#MC_MSG#MC_MSG_03','消息#短息#废件箱');
