-- 站内消息
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_INSTATIONMSG_0101');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_INSTATIONMSG_0201');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_INSTATIONMSG_0301');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_INSTATIONMSG_0401');

-- 短信
INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_MSG_0101');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_MSG_0201');

INSERT INTO PUB_ROLE_OPERATION (ROLE_ID, OPERATION_CODE) VALUES 
('MC_USER', 'MC_MSG_0301');
